# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20160623_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='update_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 23, 9, 21, 20, 340622, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
